name: EndlessSnow
version: 0.0.1
main: io.github.stuarthayhurst.endlesssnow.EndlessSnow
api-version: '1.21.10'

commands:
    deepsnow:
        description: Toggle deep snow
        usage: "Usage: /deepsnow [on / off]"
        permission: endlesssnow.deepsnow
    persistentstorm:
        description: Toggle a persistent storm
        usage: "Usage: /persistentstorm [on / off]"
        permission: endlesssnow.persistentstorm
